services:

  postgres:
    image: postgres:17
    container_name: ai-devops-postgres
    environment:
      POSTGRES_DB: ai_devops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ai-devops-redis
    ports:
      - "6380:6379"

  backend:
    build:
      context: ./backend
    image: ai-devops-backend:dev
    container_name: ai-devops-backend
    environment:
      ENVIRONMENT: local
      DEBUG: "true"
      HOST: 0.0.0.0
      PORT: 8000

      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/ai_devops
      REDIS_URL: redis://redis:6379/0

      PROVIDER: ollama
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3.2:3b

    ports:
      - "8000:8000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
