"""create devops actions table

Revision ID: 8a17cdcf9457
Revises: 8d0d29ebbcc6
Create Date: 2026-08-18 08:34:21.487386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8a17cdcf9457'
down_revision: Union[str, Sequence[str], None] = '8d0d29ebbcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devops_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], name=op.f('fk_devops_actions_analysis_id_ai_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devops_actions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devops_actions'))
    )
    op.create_index(op.f('ix_devops_actions_action'), 'devops_actions', ['action'], unique=False)
    op.create_index(op.f('ix_devops_actions_analysis_id'), 'devops_actions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_devops_actions_created_at'), 'devops_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_devops_actions_id'), 'devops_actions', ['id'], unique=False)
    op.create_index(op.f('ix_devops_actions_status'), 'devops_actions', ['status'], unique=False)
    op.create_index(op.f('ix_devops_actions_user_id'), 'devops_actions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devops_actions_user_id'), table_name='devops_actions')
    op.drop_index(op.f('ix_devops_actions_status'), table_name='devops_actions')
    op.drop_index(op.f('ix_devops_actions_id'), table_name='devops_actions')
    op.drop_index(op.f('ix_devops_actions_created_at'), table_name='devops_actions')
    op.drop_index(op.f('ix_devops_actions_analysis_id'), table_name='devops_actions')
    op.drop_index(op.f('ix_devops_actions_action'), table_name='devops_actions')
    op.drop_table('devops_actions')
    # ### end Alembic commands ###
